version: '3.8'

services: 

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      DB_HOST: mysql
      DB_NAME: mydb
      DB_USER: appuser
      DB_PASS: apppass
    ports:
        - "3306:3306"
    volumes:
        - mysql_data:/var/lib/mysql
  tomcat:
    image: tomcat:9.0
    container_name: tomcat-container
    restart: always
    depends_on:
      - mysql
    ports:
      - "8082:8080"
    volumes:
      - ./target:/usr/local/tomcat/webapps

volumes:
  mysql_data:
    
        

